### ISSUE TITLE
NNPACK for XEON W3565 (microarchitecture Nehalem)

### ISSUE THREAD

**Issue by charlyng** [Maratyszcza/NNPACK#11] opened 2016-03-30 08:15 UTC
May I know is it possible to parameterize NNPACK source code to support XEON processor without L3? I confirm XEON support AVX2.

I got error code below when running bench for XEON@ubuntu14.04
>	nnp_status_unsupported_hardware = 51,

#3 mentioned that NNPACK requires L1~3, but XEON only has L1~2, according to link below
https://software.intel.com/en-us/forums/intel-moderncode-for-parallel-architectures/topic/291067

Thank  you.

**Comment by Maratyszcza** [comment] 2016-03-30 13:35
Xeon is a marketing name for all Intel server processors released in the last 15 or so years. As such, they can base on almost any x86-64 microarchitecture. The one in your link is based on an old Harpertown microarchitecture, which indeed doesn't have L3. AFAIK, all Xeons based on Haswell/Broadwell/Skylake microarchitecture have L3 cache. Thus, it is far more likely that the error code is caused by your processor not supporting AVX2, rather than not having L3 cache. Which Xeon model do you have?

**Comment by charlyng** [comment] 2016-03-31 02:21
@Maratyszcza 

My xeon is W3565 (microarchitecture Nehalem) with L3 but does not support AVX2. This indicates the error code is most likely due to missing AVX2 as mentioned.

Thank you.

**Closed** 2016-03-31 02:23 UTC
